name: Build Arch Linux Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    
    steps:
    - name: Update system and install base dependencies
      run: |
        pacman-key --init
        pacman-key --populate archlinux
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel git sudo

    - name: Create build user
      run: |
        useradd -m builduser
        echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Fix permissions
      run: |
        chown -R builduser:builduser .
        
    - name: Install build dependencies
      run: |
        pacman -S --noconfirm nodejs npm p7zip wget icoutils imagemagick electron asar
        
    - name: Build package
      run: |
        su - builduser -c "cd $GITHUB_WORKSPACE && ./build.sh --clean no"
        
    - name: Get package info
      id: package_info
      run: |
        PKG_FILE=$(find . -maxdepth 1 -name "*.pkg.tar.*" | head -n 1)
        echo "package_file=$PKG_FILE" >> $GITHUB_OUTPUT
        echo "package_name=$(basename $PKG_FILE)" >> $GITHUB_OUTPUT
        
        # Extract version from package filename
        VERSION=$(echo "$PKG_FILE" | grep -oP 'claude-desktop-\K[0-9]+\.[0-9]+\.[0-9]+')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: claude-desktop-arch-package
        path: ${{ steps.package_info.outputs.package_file }}
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.package_info.outputs.package_file }}
        body: |
          Claude Desktop ${{ steps.package_info.outputs.version }} for Arch Linux
          
          ## Installation
          
          Download the package and install with:
          ```bash
          sudo pacman -U ${{ steps.package_info.outputs.package_name }}
          ```
          
          ## Requirements
          - Arch Linux x86_64
          - electron
          - nodejs
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
