name: Main Branch CI

on:
  push:
    branches:
      - main # Trigger on pushes to main
      - aaddrick-no_sudo # Also trigger on pushes to this branch for testing
    paths: # Trigger if relevant files change
      - 'build.sh'
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  # First, run the quick flag tests
  test-flags:
    name: Test Flags Parsing
    # Runner is defined in the called workflow (test-flags.yml)
    uses: ./.github/workflows/test-flags.yml
    # No inputs needed for test-flags.yml
 
  # Build AMD64 packages
  build-amd64:
    name: Build Packages (amd64 - ${{ matrix.flags || 'defaults' }})
    needs: test-flags # Run only if test-flags job succeeds
    # Runner is defined in the called workflow (build-amd64.yml)

    strategy:
      fail-fast: false # Allow other builds to continue if one fails
      matrix:
        include:
          - arch: amd64 # Keep arch for consistency in naming/logic if needed inside called workflow
            flags: "" # Defaults (deb, clean=yes)
          - arch: amd64
            flags: "--build appimage --clean no"

    uses: ./.github/workflows/build-amd64.yml # Call the dedicated amd64 workflow
    with:
      build_flags: ${{ matrix.flags }}
    # Secrets are not automatically passed to reusable workflows, pass if needed
    # secrets: inherit

  # Build ARM64 packages
  build-arm64:
    name: Build Packages (arm64 - ${{ matrix.flags || 'defaults' }})
    needs: test-flags # Run only if test-flags job succeeds
    # Runner is defined in the called workflow (build-arm64.yml)

    strategy:
      fail-fast: false # Allow other builds to continue if one fails
      matrix:
        include:
          - arch: arm64 # Keep arch for consistency in naming/logic if needed inside called workflow
            flags: "--clean no"
          - arch: arm64
            flags: "--build appimage"

    uses: ./.github/workflows/build-arm64.yml # Call the dedicated arm64 workflow
    with:
      build_flags: ${{ matrix.flags }}
    # Secrets are not automatically passed to reusable workflows, pass if needed
    # secrets: inherit