name: Main Branch CI

on:
  push:
    branches:
      - main # Trigger on pushes to main
      - aaddrick-no_sudo # Also trigger on pushes to this branch for testing
    paths: # Trigger if relevant files change
      - 'build.sh'
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  # First, run the quick flag tests
  test-flags:
    name: Test Flags Parsing
    uses: ./.github/workflows/test-flags.yml
    # No inputs needed for test-flags.yml

  # Then, run the actual builds after flags are confirmed okay
  build-packages:
    name: Build Packages (${{ matrix.arch }} - ${{ matrix.flags || 'defaults' }})
    needs: test-flags # Run only if test-flags job succeeds
    # Dynamically select runner based on matrix architecture
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}

    strategy:
      fail-fast: false # Allow other builds to continue if one fails
      matrix:
        include:
          - arch: arm64
            flags: "--clean no"
          - arch: arm64
            flags: "--build appimage"
          - arch: amd64
            flags: "" # Defaults (deb, clean=yes)
          - arch: amd64
            flags: "--build appimage --clean no"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Reusable Build Workflow
        uses: ./.github/workflows/build-package.yml
        with:
          # target_arch is no longer needed, build.sh auto-detects
          build_flags: ${{ matrix.flags }}
        # Secrets are not automatically passed to reusable workflows, pass if needed
        # secrets: inherit